export const SET_SUBJECTS = 'SET_SUBJECTS';
export const SET_NODE_DISTANCE = 'SET_NODE_DISTANCE';
export const SET_ZOOM_DEPTH = 'SET_ZOOM_DEPTH';
export const CHANGE_ENABLE_DRAG = 'CHANGE_ENABLE_DRAG';
export const CHANGE_PULL_IN = 'CHANGE_PULL_IN';
